
export enum PeriodicityEnum {
    DE_MINUTOS_EM_MINUTOS = 12,
    DE_HORAS_EM_HORAS = 13,
    DIARIAMENTE = 1,
    SEMANALMENTE = 2,
    MENSALMENTE = 3,
    BIMESTRALMENTE = 4,
    TRIMESTRALMENTE = 5,
    SEMESTRALMENTE = 6,
    ANUALMENTE = 7,
    DURANTE_FDS = 8,
    TODA_SEMANA_EXCETO_FDS = 9,
    APENAS_DIAS_UTEIS = 14,
    PRIMEIRO_DIA_ANO = 10,
    ULTIMO_DIA_ANO = 11
}
